version: '3'
services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "qthibeault/${COMPOSE_PROJECT_NAME}/ros:humble"

    volumes:
      - type: bind
        source: .
        target: /workspace

    init: true
    command: ["tail", "-f", "/dev/null"]
    working_dir: /workspace
    container_name: ${COMPOSE_PROJECT_NAME}-ros
