[tool.black]
line-length = 120

[tool.ruff]
src = ["src/detector", "src/predictor"]
select = ["F", "E", "I", "ANN", "B", "A", "COM", "C4", "SIM", "TCH"]
line-length = 100
target-version = "py310"

[tool.ruff.flake8-annotations]
mypy-init-return = true
suppress-none-returning = true

[tool.pyright]
include = [
    "./src/detector/detector",
    "./src/predictor/predictor",
    "./src/converter/converter"
]
pythonVersion = "3.10"
pythonPlatform = "Linux"
extraPaths = ["./vendor/rclpy/rclpy"]
stubPath = "./src/stubs"

reportMissingModuleSource = false
reportMissingTypeStubs = true
