[tool.black]
line-length = 100

[tool.ruff]
src = ["src/**/*.py"]
select = ["F", "E", "I", "ANN", "B", "A", "COM", "C4", "SIM", "TCH"]
ignore = ["ANN101"]
line-length = 100
target-version = "py310"

[tool.ruff.flake8-annotations]
mypy-init-return = true
suppress-none-returning = true

[tool.pyright]
include = ["src/**/*.py"]
pythonVersion = "3.10"
pythonPlatform = "Linux"
stubPath = "./src/stubs"
