[tool.black]
line-length = 100

[tool.ruff]
src = ["src/detector", "src/predictor"]

[tool.pyright]
include = ["./src/detector/detector", "./src/predictor/predictor"]
stubPath = "./stubs"

[tool.mypy]
mypy_path = "stubs"
files = ["src/detector/detector", "src/predictor/predictor"]
strict = true
