version: '3'

vars:
  SERVICE_NAME: 'ros'
  UID_GID:
    sh: stat -c "%u:%g" {{.ROOT_DIR}}/Dockerfile
  BUILD_CMD: 'docker compose run --rm --user {{.UID_GID}} {{.SERVICE_NAME}} colcon build --packages-select'

tasks:
  setup:
    cmds:
      - docker compose build {{.SERVICE_NAME}}
      - git submodule update --init --recursive
      - pipenv install

  build-detector:
    cmds:
      - '{{.BUILD_CMD}} detector'
    sources:
      - src/detector/detector/*.py
    generates:
      - build/detector/build/lib/detector/*.py

  build-predictor:
    cmds:
      - '{{.BUILD_CMD}} predictor'
    sources:
      - src/predictor/predictor/*.py
    generates:
      - build/predictor/build/lib/predictor/*.py

  build-all:
    deps:
      - build-detector
      - build-predictor

  clean-image:
    cmds:
      - docker compose down --rmi all --remove-orphans

  clean-build:
    cmds:
      - rm -rf ./build ./install ./log

  clean-all:
    deps:
      - clean-image
      - clean-build
