version: '3'

vars:
  SERVICE_NAME: 'ros'
  UID:
    sh: id --user
  GID:
    sh: id --group
  UID_GID: '{{.UID}}:{{.GID}}'
  RUN_CMD: 'docker compose run --user "{{.UID_GID}}"'
  BUILD_CMD: '{{.RUN_CMD}} --rm {{.SERVICE_NAME}} colcon build --packages-select'

tasks:
  setup:
    cmds:
      - docker compose build {{.SERVICE_NAME}}
      - git submodule update --init --recursive
      - pipenv install

  build-detector:
    cmds:
      - '{{.BUILD_CMD}} detector'
    sources:
      - src/detector/detector/*.py
    generates:
      - build/detector/build/lib/detector/*.py

  build-predictor:
    cmds:
      - '{{.BUILD_CMD}} predictor'
    sources:
      - src/predictor/predictor/*.py
    generates:
      - build/predictor/build/lib/predictor/*.py

  build-converter:
    cmds:
      - '{{.BUILD_CMD}} converter'
    sources:
      - src/converter/converter/*.py
    generates:
      - build/converter/build/lib/converter/*.py

  build-all:
    deps:
      - build-detector
      - build-predictor
      - build-converter

  clean-image:
    cmds:
      - docker compose down --rmi all --remove-orphans

  clean-build:
    cmds:
      - rm -rf ./build ./install ./log

  clean-all:
    deps:
      - clean-image
      - clean-build
