CAP_PROP_FPS: int
CAP_PROP_FRAME_WIDTH: int
CAP_PROP_FRAME_HEIGHT: int

class Mat: ...

class VideoCapture:
    def __init__(self, filename: str | int): ...
    def read(self) -> tuple[bool, Mat]: ...
    def isOpened(self) -> bool: ...
    def release(self): ...
    def get(self, prop: int) -> float: ...

class VideoWriter_fourcc:
    def __init__(self, *args: str): ...

class VideoWriter:
    def __init__(
        self,
        filename: str,
        codec: VideoWriter_fourcc,
        fps: int,
        dims: tuple[int, int],
    ): ...
    def write(self, frame: Mat) -> None: ...
    def release(self) -> None: ...

def imshow(img: Mat): ...
