from typing import overload

class Weights: ...

class Size(tuple): ...

class Tensor:
    def unsqueeze(self, dim: int) -> Tensor: ...
    @overload
    def size(self) -> Size: ...
    @overload
    def size(self, dim: int) -> int: ...
    @property
    def ndim(self) -> int: ...
    def __getitem__(self, value: int) -> Tensor: ...
    def item(self) -> float: ...

class FloatTensor(Tensor): ...
class Int64Tensor(Tensor): ...
class UInt8Tensor(Tensor): ...
