CAP_PROP_FPS: int
CAP_PROP_FRAME_WIDTH: int
CAP_PROP_FRAME_HEIGHT: int

class Mat:
    def copy(self) -> Mat: ...

class VideoCapture:
    def __init__(self, filename: str | int): ...
    def read(self) -> tuple[bool, Mat]: ...
    def isOpened(self) -> bool: ...
    def release(self): ...
    def get(self, prop: int) -> float: ...

class VideoWriter_fourcc:
    def __init__(self, *args: str): ...

class VideoWriter:
    def __init__(
        self,
        filename: str,
        codec: VideoWriter_fourcc,
        fps: int,
        dims: tuple[int, int],
    ): ...
    def write(self, frame: Mat) -> None: ...
    def release(self) -> None: ...
    def close(self) -> None: ...

def destroyAllWindows(): ...
def imshow(window_name: str, img: Mat): ...
def rectangle(
    img: Mat,
    start_point: tuple[float, float],
    end_point: tuple[float, float],
    color: tuple[int, int, int],
    thickness: int
): ...
def circle(
    img: Mat,
    center: tuple[float, float],
    radius: float,
    color: tuple[int, int, int],
    thickness: int
): ...
def line(
    img: Mat,
    pt1: tuple[float, float],
    pt2: tuple[float, float],
    color: tuple[int, int, int],
    thickness: int
): ...
